name: "Main workflow"
on:
  pull_request:
  push:
    branches:
      - main
env:
  FORCE_COLOR: 2
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "npm"
      - name: NPM install
        run: npm ci --force
      - name: Lint
        run: |
          npm run lint
          npm run prettier
  api:
    runs-on: ubuntu-latest
    needs: lint
    defaults:
      run:
        working-directory: packages/api
    steps:
      - uses: actions/checkout@v3
  e2e:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "npm"
      - name: NPM install
        run: npm ci --force
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        working-directory: packages/frontend
        with:
          install: false
          config: baseUrl=http://localhost:3000
          start: npm start
          command: npx cypress run
          browser: chrome
          project: ./packages/e2e
      - name: Archive Cypress screenshots (on failure)
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Archive Cypress video recordings
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
  frontend:
    runs-on: ubuntu-latest
    needs: lint
    defaults:
      run:
        working-directory: packages/frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "npm"
      - name: Prepare env vars
        run: |
          touch .env
          echo REACT_APP_OPENWEATHERMAP_API_KEY=${{ secrets.REACT_APP_OPENWEATHERMAP_API_KEY }} > .env
      - name: NPM install
        run: npm ci --force
      - name: Unit tests
        run: npm run tests-with-coverage
      - name: Build
        run: npm run build
      - name: Upload coverage (Codecov)
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: true
          verbose: true
      - name: Deploy to Firebase (Pull Request)
        if: "${{ github.event_name == 'pull_request' }}"
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_REACT_GRAPHQL_PLAYGROUND }}"
          projectId: react-graphql-playground
      - name: Deploy to Firebase (main)
        if: "${{ github.ref == 'refs/heads/main' }}"
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_REACT_GRAPHQL_PLAYGROUND }}"
          channelId: live
          projectId: react-graphql-playground
