name: "Build & test"
on:
  pull_request:
  push:
    branches:
      - main
env:
  FORCE_COLOR: 2
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "npm"
      - name: NPM install
        run: npm ci --force
      - name: Lint
        run: |
          npm run lint
          npm run prettier
      - name: Unit tests
        run: npm run tests-with-coverage
      - name: Build
        run: npm run build
      - name: Upload coverage (Codecov)
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/clover.xml
          fail_ci_if_error: true
          verbose: true
      - name: Deploy to Firebase (Pull Request)
        if: "${{ github.event_name == 'pull_request' }}"
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_REACT_GRAPHQL_PLAYGROUND }}"
          projectId: react-graphql-playground
      - name: Deploy to Firebase (main)
        if: "${{ github.ref == 'ref/heads/main' }}"
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_REACT_GRAPHQL_PLAYGROUND }}"
          channelId: live
          projectId: react-graphql-playground
